### ISSUE TITLE
Fail assert by object equals

### ISSUE THREAD

**Issue by disc99** [disc99/table-setup#4]
Case:

``` groovy
def "expect table"() {
    setup:
    sql.dataSet("sales").add(id: 200, day: '2016-04-01', item_id: 100, create_at: new Date(1))
    sql.dataSet("sales").add(id: 201, day: '2016-04-02', item_id: 101, create_at: new Date(1))

    expect:
    db.expect {
        sales:
        id  | day          | item_id | create_at
        200 | '2016-04-01' | 100     | new Date(1)
        201 | '2016-04-02' | 101     | new Date(1)
    }
}
```

Output:

```
Assertion failed: 

assert actual == expected
       |      |  |
       |      |  [[ID:200, DAY:2016-04-01, ITEM_ID:100, CREATE_AT:1970-01-01], [ID:201, DAY:2016-04-02, ITEM_ID:101, CREATE_AT:1970-01-01]]
       |      false
       [[ID:200, DAY:2016-04-01, ITEM_ID:100, CREATE_AT:1970-01-01], [ID:201, DAY:2016-04-02, ITEM_ID:101, CREATE_AT:1970-01-01]]

    at io.disc99.hogan.Database.expect_closure2(Database.groovy:148)
    at groovy.lang.Closure.call(Closure.java:426)
    at io.disc99.hogan.Database.expect(Database.groovy:137)
    at io.disc99.hogan.DatabaseSpec.expect table(DatabaseSpec.groovy:66)
```

Cause:

``` groovy
new Date(1) != new Date(1)
```

**Comment by disc99** [comment]
OK
